---
name: renovate-issue-action
on:
  pull_request:
    branches: [main]
    types:
    - closed
permissions:
  issues: write
  contents: read
jobs:
  renovate-issue-action:
    if: github.event.pull_request.user.login == 'renovate[bot]'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: aquaproj/aqua-installer@v1.0.0
      with:
        aqua_version: v1.5.1
    - run: renovate-issue-action
      env:
        GITHUB_TOKEN: ${{ github.token }}
